
openapi: 3.0.0
info:
  title: Job Portal API - Admin Endpoints
  version: 1.0.0
  description: Admin-related endpoints for the Job Portal API
servers:
  - url: http://localhost:5000
    description: Development server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /api/admin/auth/login:
    post:
      summary: Admin login
      tags:
        - Admin
      operationId: loginAdmin
      description: Authenticates an admin and returns a JWT token (handled by auth.controller.ts)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: admin@example.com
                password:
                  type: string
                  example: admin123
              required:
                - email
                - password
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIs...
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid credentials
  /api/admin/jobs:
    post:
      summary: Create a new job
      tags:
        - Admin
      operationId: createJob
      description: Creates a new job posting (handled by job.controller.ts, requires adminAuth)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: Software Engineer
                company:
                  type: string
                  example: Tech Corp
                location:
                  type: string
                  example: New York
                description:
                  type: string
                  example: Develop web applications
              required:
                - title
                - company
                - location
                - description
      responses:
        '201':
          description: Job created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Job created successfully
                  job:
                    type: object
                    properties:
                      id:
                        type: string
                      title:
                        type: string
                      company:
                        type: string
                      location:
                        type: string
                      description:
                        type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthorized
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Title too short
  /api/admin/jobs/{id}:
    delete:
      summary: Delete a job
      tags:
        - Admin
      operationId: deleteJob
      description: Deletes a job posting by ID (handled by job.controller.ts, requires adminAuth)
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Job ID
      responses:
        '200':
          description: Job deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Job deleted successfully
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthorized
        '404':
          description: Job not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Job not found
  /api/admin/interviews:
    post:
      summary: Schedule an interview
      tags:
        - Admin
      operationId: scheduleInterview
      description: Schedules an interview for a user and job (handled by interview.controller.ts, requires adminAuth)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                jobId:
                  type: string
                  example: 12345
                userId:
                  type: string
                  example: 67890
                date:
                  type: string
                  format: date
                  example: 2025-05-01
              required:
                - jobId
                - userId
                - date
      responses:
        '201':
          description: Interview scheduled successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Interview scheduled successfully
                  interview:
                    type: object
                    properties:
                      jobId:
                        type: string
                      userId:
                        type: string
                      date:
                        type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthorized
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid job ID
