
openapi: 3.0.0
info:
  title: Job Portal API - Superadmin Endpoints
  version: 1.0.0
  description: Superadmin-related endpoints for the Job Portal API
servers:
  - url: http://localhost:5000
    description: Development server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /api/superadmin/users/{id}:
    delete:
      summary: Delete a user
      tags:
        - Superadmin
      operationId: deleteUser
      description: Deletes a user account by ID (handled by user.controller.ts, requires superAdminAuth)
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: User ID
      responses:
        '200':
          description: User deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User deleted successfully
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthorized
        '404':
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User not found
  /api/superadmin/admins/{id}:
    delete:
      summary: Delete an admin
      tags:
        - Superadmin
      operationId: deleteAdmin
      description: Deletes an admin account by ID (handled by admin.controller.ts, requires superAdminAuth)
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Admin ID
      responses:
        '200':
          description: Admin deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Admin deleted successfully
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthorized
        '404':
          description: Admin not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Admin not found
  /api/superadmin/jobs/{id}:
    delete:
      summary: Delete a job
      tags:
        - Superadmin
      operationId: deleteJobSuperadmin
      description: Deletes a job posting by ID (handled by job.controller.ts, requires superAdminAuth)
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Job ID
      responses:
        '200':
          description: Job deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Job deleted successfully
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthorized
        '404':
          description: Job not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Job not found
  /api/superadmin/analytics:
    get:
      summary: Get analytics
      tags:
        - Superadmin
      operationId: getAnalytics
      description: Retrieves analytics data for the platform (handled by analytic.controller.ts, requires superAdminAuth)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Analytics data
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalUsers:
                    type: integer
                    example: 100
                  totalJobs:
                    type: integer
                    example: 50
                  totalApplications:
                    type: integer
                    example: 200
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthorized
  /api/superadmin/reports:
    get:
      summary: Get reports
      tags:
        - Superadmin
      operationId: getReports
      description: Retrieves reports for the platform (handled by report.controller.ts, requires superAdminAuth)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Reports data
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    generatedAt:
                      type: string
                      format: date-time
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthorized
